name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-18.04
    steps:
      - id: download-fly
        run: |
          apt-get install curl;
          curl 'http://localhost:8080/api/v1/cli?arch=amd64&platform=linux' -o fly;
          chmod +x ./fly
      - id: trigger-job
        run: |
          fly -t demo trigger-job --job dev-pipeline/build --watch
